---
name: minio
director_uuid: fb70f16a-4d6f-41f8-bc2e-0181a03dff18 

releases:
- name: minio
  version: latest

networks:
- name: default
  subnets:
  - range: 10.244.0.0/28
    reserved: [10.244.0.1]
    static: [10.244.0.2,10.244.0.6,10.244.0.10]
    cloud_properties:
      name: random

resource_pools:
- name: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  network: default
  cloud_properties: {}

compilation:
  workers: 2
  network: default
  cloud_properties: {}

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 2

jobs:
- name: minio-server
  templates:
  - name: minio-server
  instances: 1
  resource_pool: default
  networks:
  - name: default
    static_ips:
    - 10.244.0.2
  properties:
    credentials:
      accesskey: GESNKCXX4LMNRYBI1YR0
      secretkey: U43jymLJ+1ZwzHj1vEILHcHjsSWxWThtxVD3CBxj
    region: us-east-1
